### ISSUE TITLE
搭建完成后访问 91porn.php显示500错误

### ISSUE THREAD

**Issue by rainlgtao** [zzjzz9266a/91porn_php#1]
搭建完成后访问 91porn.php显示500错误；
访问91all.php 显示如下：
http://91porn.com/v.php?category=top&viewtype=basic&page=1 exception 'InvalidArgumentException' with message 'DiDom\Document::load expects parameter 4 to be integer, string given' in /home/wwwroot/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php:235 Stack trace: #0 /home/wwwroot/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load('http://91porn.c...', true, 'html') #1 /home/wwwroot/91porn/91all.php(29): DiDom\Document->__construct('http://91porn.c...', true, 'Accept-Language...') #2 /home/wwwroot/91porn/91all.php(48): listPage('http://91porn.c...') #3 {main} http://91porn.com/v.php?category=top&viewtype=basic&page=1&page=2 exception 'InvalidArgumentException' with message 'DiDom\Document::load expects parameter 4 to be integer, string given' in /home/wwwroot/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php:235 Stack trace: #0 /home/wwwroot/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load('http://91porn.c...', true, 'html') #1 /home/wwwroot/91porn/91all.php(29): DiDom\Document->__construct('http://91porn.c...', true, 'Accept-Language...') #2 /home/wwwroot/91porn/91all.php(48): listPage('http://91porn.c...') #3 {main} http://91porn.com/v.php?category=top&viewtype=basic&page=1&page=2&page=3 exception 'InvalidArgumentException' with message 'DiDom\Document::load expects parameter 4 to be integer, string given' in /home/wwwroot/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php:235 Stack trace: #0 /home/wwwroot/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load('http://91porn.c...', true, 'html') #1 /home/wwwroot/91porn/91all.php(29): DiDom\Document->__construct('http://91porn.c...', true, 'Accept-Language...') #2 /home/wwwroot/91porn/91all.php(48): listPage('http://91porn.c...') #3 {main} http://91porn.com/v.php?category=top&viewtype=basic&page=1&page=2&page=3&page=4 exception 'InvalidArgumentException' with message 'DiDom\Document::load expects parameter 4 to be integer, string given' in /home/wwwroot/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php:235 Stack trace: #0 /home/wwwroot/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load('http://91porn.c...', true, 'html') #1 /home/wwwroot/91porn/91all.php(29): DiDom\Document->__construct('http://91porn.c...', true, 'Accept-Language...') #2 /home/wwwroot/91porn/91all.php(48): listPage('http://91porn.c...') #3 {main} http://91porn.com/v.php?category=top&viewtype=basic&page=1&page=2&page=3&page=4&page=5 exception 'InvalidArgumentException' with message 'DiDom\Document::load expects parameter 4 to be integer, string given' in /home/wwwroot/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php:235 Stack trace: #0 /home/wwwroot/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load('http://91porn.c...', true, 'html') #1 /home/wwwroot/91porn/91all.php(29): DiDom\Document->__construct('http://91porn.c...', true, 'Accept-Language...') #2 /home/wwwroot/91porn/91all.php(48): listPage('http://91porn.c...') #3 {main} http://91porn.com/v.php?category=top&viewtype=basic&page=1&page=2&page=3&page=4&page=5&page=6 exception 'InvalidArgumentException' with message 'DiDom\Document::load expects parameter 4 to be integer, string given' in /home/wwwroot/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php:235 Stack trace: #0 

请问是哪的原因，谢谢

**Comment by rainlgtao** [comment]
Fatal error: Uncaught exception 'InvalidArgumentException' with message 'DiDom\Document::load expects parameter 4 to be integer, string given' in /www/wwwroot/vendor/imangazaliev/didom/src/DiDom/Document.php:235 Stack trace: #0 /www/wwwroot/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load('http://91porn.c...', true, 'html') #1 /www/wwwroot/91porn.php(21): DiDom\Document->__construct('http://91porn.c...', true, 'User-Agent:Mozi...') #2 /www/wwwroot/91porn.php(33): listPage() #3 {main} thrown in /www/wwwroot/vendor/imangazaliev/didom/src/DiDom/Document.php on line 235

**Comment by zzjzz9266a** [comment]
已解决，请更新到最新~~
