### ISSUE TITLE
运行错误 PHP 7.3.5 node12.2.0

### ISSUE THREAD

**Issue by Unlash** [zzjzz9266a/91porn_php#24]
![图片](https://user-images.githubusercontent.com/32661990/57428077-43672600-7259-11e9-8415-873a7c346b89.png)

下载单个视频文件 也不行
![图片](https://user-images.githubusercontent.com/32661990/57428655-f0db3900-725b-11e9-99e4-64771dab0e38.png)

**Comment by zzjzz9266a** [comment]
看下这个https://www.cnblogs.com/wangshuyi/p/6822061.html

**Comment by Unlash** [comment]
> 
> 
> 看下这个https://www.cnblogs.com/wangshuyi/p/6822061.html

我没有web服务器
我是用scoop 安装的 php
![图片](https://user-images.githubusercontent.com/32661990/57428795-7f4fba80-725c-11e9-85ad-4bce871ed390.png)

**Comment by zzjzz9266a** [comment]
不需要，只要把php的curl扩展打开就行

**Comment by zzjzz9266a** [comment]
不需要，只要把php的curl扩展打开就行

**Comment by Unlash** [comment]
> 
> 
> 不需要，只要把php的curl扩展打开就行

![图片](https://user-images.githubusercontent.com/32661990/57429480-d9ea1600-725e-11e9-9f16-d7f46f6ca51b.png)


已解决 手动指定模块路径

**Comment by Unlash** [comment]
![图片](https://user-images.githubusercontent.com/32661990/57429535-0f8eff00-725f-11e9-84b3-d25cfa7d0c2d.png)


这个web aria2 为什么一直显示加载
cli的aria2 有显示进度

**Comment by Unlash** [comment]
![图片](https://user-images.githubusercontent.com/32661990/57429592-436a2480-725f-11e9-9682-be0eccb3111e.png)


还有几个错误。

**Comment by Unlash** [comment]
抓取下载的视频好模糊

**Comment by Unlash** [comment]
![图片](https://user-images.githubusercontent.com/32661990/57429716-d5722d00-725f-11e9-9ce2-ed2d003a8cb1.png)

**Comment by Unlash** [comment]
![图片](https://user-images.githubusercontent.com/32661990/57431863-bc20af00-7266-11e9-829b-6bca51f551a1.png)

**Comment by zzjzz9266a** [comment]
我觉得你的问题应该跟这位 #22  是一样的，我在windows下测试跟你一样，应该是aria2的问题

**Comment by Unlash** [comment]
> 
> 
> 我觉得你的问题应该跟这位 #22 是一样的，我在windows下测试跟你一样，应该是aria2的问题

为什么拉下来的视频 很模糊。

**Comment by zzjzz9266a** [comment]
只要视频下载完成就是这样，91服务器上什么样就是什么样
