### ISSUE TITLE
运行出错  php 7.2 nodejs 12

### ISSUE THREAD

**Issue by yurimoe** [zzjzz9266a/91porn_php#40]
php detailPage.php http://91porn.com/view_video.php?viewkey=042a30e56c9cd20b075f
没有分享链接
PHP Fatal error:  Uncaught Error: Call to a member function text() on null in /home/91porn_php/detailPage.php:32
Stack trace:
#0 /home/91porn_php/detailPage.php(125): singlePage('http://91porn.c...', '')
#1 {main}
  thrown in /home/91porn_php/detailPage.php on line 32

Fatal error: Uncaught Error: Call to a member function text() on null in /home/91porn_php/detailPage.php:32
Stack trace:
#0 /home/91porn_php/detailPage.php(125): singlePage('http://91porn.c...', '')
#1 {main}
  thrown in /home/91porn_php/detailPage.php on line 32

而
php 91porn.php

没有任何的回显信息

**Comment by sewujishipin** [comment]
脚本失效了
