### ISSUE TITLE
拉取了最新代码，下载出错请指导下

### ISSUE THREAD

**Issue by usbcdrom** [zzjzz9266a/91porn_php#41]
没有做任何修改的情况下运行 php 91porn.php
![QQ截图20190820225133](https://user-images.githubusercontent.com/43695445/63358129-20dac200-c39d-11e9-94aa-e6349bfe9c50.jpg)
![QQ截图20190820225154](https://user-images.githubusercontent.com/43695445/63358132-21735880-c39d-11e9-8adf-43448ad1a924.jpg)

**Comment by deemoartisan** [comment]
请问怎么解决的？
